[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "epygram"
version = "1.4.22"
description = "EPyGrAM : Enhanced Python for Graphics and Analysis of Meteorological fields"
authors = [
    { name = "Alexandre MARY", email = "a.mary@meteo.fr" },
    { name = "Sébastien Riette"  , email = "s.riette@meteo.fr"}
]
maintainers = [
  { name = "Alexandre MARY", email = "a.mary@meteo.fr" }, 
  {name = "Walid CHIKHI", email = "waliidchikhi@gmail.com" }
]

readme = "README.md"
license = {file = "LICENSE.txt"}


requires-python = ">=3.7"
dependencies=[
"taylorism",
"footprints",
"bronx",
"numpy",
"cartopy == 0.23.0",
"matplotlib == 3.8.4",
"eccodes",
"vtk",
"vortex",
"pillow",
"contourpy",
"h5py",
"netCDF4",
"pyproj",
"pyresample",
"scipy",
"six",
"web.py",
]

[tool.coverage.run]
source = ["src"]
[project.urls]
documentation = "https://umr-cnrm.github.io/EPyGrAM-doc"
source = "https://github.com/UMR-CNRM/EPyGrAM.git"
download = "https://github.com/UMR-CNRM/EPyGrAM/releases"
tracker = "https://github.com/UMR-CNRM/EPyGrAM/issues"

[tool.pytest.ini_options]
testpaths = [
    "tests"
]
[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
